
// This data is generated by LLM models after analyzing the reviews within a time range
export interface RecurringIssue {
    notes: RecurringIssueNotes;
    listingId: number;
    id: number;
}

export interface RecurringIssueNotes {
    summary: string;
    class: 'negative' | 'neutral' | 'positive';
}